### ISSUE TITLE
Broken mod compatibility because of hardcoded value

### ISSUE THREAD

**Issue by zabi94** [CursedFlames/BountifulBaubles#10]
https://github.com/CursedFlames/BountifulBaubles/blob/c6ffd074915989c3b3bb18d61aceec97bdbee121/src/main/java/cursedflames/bountifulbaubles/event/EventHandler.java#L32

This line shouldn't have a hardcoded `7` as the baubles slot limit, `baubles.getSlots()` should be used instead. This allows compat with mods like [Bring me the rings!](https://minecraft.curseforge.com/projects/bring-me-the-rings) that expand the baubles slots

**Comment by CursedFlames** [comment]
fixed with 0c0560d
