### ISSUE TITLE
[Suggestion] Some kind of item to recover some lost health from the 'Broken Heart" Bauble.

### ISSUE THREAD

**Issue by SonicX8000** [CursedFlames/BountifulBaubles#11]
While sleeping restores all lost health I was curious if there could be some sort of item to allow you to patch up some lost health without having to sleep it off. Like a bandage or something.

Since the Broken Heart uses it's own Health Modifier. Say it's value is at -18.2 which would mean you have 1.8/1.8 max health and you use an item to restore 4.0 lost health. That value will change from -18.2 to -14.2 which means your health will be 1.8/5.8. Note that this item ONLY restores lost health that was done via the Broken Heart.

This item could also have some sort of cooldown where if you use it enough times you will be unable to use it until either a in-game day goes by or you sleep it off. This is in case one is traveling in a dimension where sleeping is... how should I say... unwise.

The cooldown time + amount you can use could be configurable in a way, especially if one disables the sleeping option.

**Comment by SonicX8000** [comment]
Just curious if this was still being considered.

**Comment by CursedFlames** [comment]
I currently have no plans to implement methods of healing broken heart damage other than sleeping. Note that in 1.14, sleeping heals a configurable amount, rather than all of the lost health.

**Comment by SonicX8000** [comment]
Aww... would've been nice to have in a pinch if exploring a dimension or something.
