### ISSUE TITLE
crash on using recall potion in different dimension

### ISSUE THREAD

**Issue by Shivaxi** [CursedFlames/BountifulBaubles#13]
If you use a recall potion in a different dimension (I was testing while in the lost cities dimension) it crashes your game.  Upon restarting though you do end up in the overworld at least lol.

Also it doesn't work with Waystones I thought I'd add, some compatibility if possible would be cool, since a Waystone can act as your spawn point.

I haven't tested yet if the wormhole potion and mirror item also crash when using in other dimensions.

**Comment by CursedFlames** [comment]
Should be fixed with a786abb, which will be in the next release (v0.1.1), whenever that happens.
