### ISSUE TITLE
Suggestion - Add some sort of accept/deny feature when someone uses a Wormhole Potion

### ISSUE THREAD

**Issue by maxerium** [CursedFlames/BountifulBaubles#14]
Basically what the title explains. Wormhole Potions are a deadly thing on my heap of RLCraft servers since they tend to get abused alot.

Adding an accept/deny functionality to the person who gets the teleport "request" would also make this part of the mod more server-friendly. :)

**Comment by CursedFlames** [comment]
I've started work on this with 3d564e0, I'll polish it and do more testing and then release it in v0.1.1.

**Comment by Shivaxi** [comment]
thank you, i appreciate it!

**Comment by CursedFlames** [comment]
v0.1.1 is now released.
