### ISSUE TITLE
Jump height not stacking with other mods features correctly

### ISSUE THREAD

**Issue by Maniacer2** [CursedFlames/BountifulBaubles#16]
Hi, I'm a RLCraft modpack player reporting a bug.

From Better Survival mod, there's an enchant "High jump" which increases jump height.
From BountifulBaubles mod, there's a balloon which increases jump height.
From Quality Tools mod, there's a quality for bauble items and for leggings which increases jump height by 0,5 block per quality.

I've just finished doing some testing, main result is: when jump height is increased by 1 full block from item qualities(Quality Tools mod), Balloon and High Jump enchant completly stops working.
With Balloon only equiped(without jump boost quality), I can jump 3 blocks at once.
With High Jump II enchant only on boots, I can jump 2,5 blocks at once
With Balloon and High Jump II enchant, I can jump 5 blocks at once. This means High Jump enchant and Balloon stacks.

However, when system detects at least 2 qualities which increase jump height(either on 2 other items or balloon + 1 other item), High Jump and Balloon are disabled.

While playing survival, I made some baubles and was able to jump 4 blocks at once(+3 block jump total), but friend found a balloon from a dungeon. I equiped it and my jump wasn't increased by it(quality disabled it). I equiped balloon only, then it worked. Equiped my baubles with quality and it stopped working.

I simply could play with High Jump and Balloon since they stack while avoiding jump height quality on everything, but there's a quality giving jump height and speed at once, which I really want to use to be jumpy and speedy at once(also 2 potion rings of speed).

Copying & pasting this message to all mods related.

**Comment by CursedFlames** [comment]
Haven't done any testing yet, but I suspect that this might be due to PotionCore (which QualityTools depends on) adding a player attribute for jump height, causing all other jump boosts to be ignored. If that's the case, I think this would have to be fixed on their end.

**Comment by CursedFlames** [comment]
Closing as 1.12 is no longer supported.
