### ISSUE TITLE
[1.12.2] Bauble oddity & some baubles not working correctly if using the Extra Bauble Slots via "Bring me the rings'.

### ISSUE THREAD

**Issue by SonicX8000** [CursedFlames/BountifulBaubles#17]
Minecraft: 1.12.2
Forge: 14.23.5.2847

Mods:
Baubles-1.12-1.5.2
Botania+r1.10-362
Bountiful+Baubles-1.12.2-0.1.2
BringMeTheRings-0.4
FlameLib-1.12.2-0.0.7
jei_1.12.2-4.15.0.291

-----

Bring me the rings is a mod that adds in extrat ring slots for your baubles, meaning you can wear more 'ring' or 'any' baubles, if you wish... However not all the effects work when worn in the extra slots. Here's a list of baubles that are effected.

***Baubles tested***

*Balloon*
Both: You can jump higher but to reduce the fall damage you need to jump off the cliffs, walking off them will deal the full fall damage to you.

*Obsidian Skull*
Main: Immune to Fire & being on fire. Fire Damage from say... a Blaze Fireball is reduced.
Extra: No Effect, meaning you can take damage from standing in a fire, being set on fire and Fire Damage is not reduced.

*Ring of Overclocking*
Both: Immune to Slowness but the +7% Speed seems to stay even if you remove the ring.

*Flywheel + Advanced Flywheel
Both: Charges items that requires RF... however it seems that when you equip them the tooltip & durability bar bugs out. For example...

Advanced Fly wheel shows as "?a8000000/8000000RF" but when equipped it'll glitch to "?40/8000000RF" sometimes. Seems to be visual as it'll still charge items.

-----

Another thing I noticed when equipping the baubles that has an 'quality' like granting an extra half heart or half armor, the sometimes the bars will flash repeatedly for a couple seconds. It doesn't happen all the time however.

**Comment by SonicX8000** [comment]
Perhaps this fits under this as well.

*EDIT*
Can rule out the Scaling Health conflict having seen the comment mentioning that only half a heart or less of Fire Damage is blocked so if the damage was scaled up, the Skull & Shield will no longer protect you from burning up.

-----

On another note, with just "Baubles" & "Bountiful Baubles" installed... I've had the Knockback Resist not work at all when equipped as a bauble but if it's in your hands... the Knockback Resist works. This may be random as when I first made this issue while testing out the baubles with 'Bring me the rings' mod... the Knockback Resist did work as a bauble in either the Main or Extra Slots. *shrugs*

**Comment by CursedFlames** [comment]
The balloon not decreasing fall damage when you walk off cliffs is an issue in regular slots too, and one that I'm not sure how to deal with without negating fall damage completely. Will look into that at some point.

Obsidian Skull should hopefully be fixed with eb31b0e.

The code that handles attribute modifiers on items (cobalt shield knockback resist, overclocking ring speed, etc.) is kinda spaghetti, so I'm not sure what exactly is causing the inconsistencies.

The flywheel charge display is already buggy when equipped in regular baubles slots, I'm not sure why. Something to do with NBT syncing, probably

**Comment by SonicX8000** [comment]
Gave the update a go, Obsidian Skull & Shield now work from the Extra Bauble Slots with protecting you from burning up.

Has the Obsidian Shield always had the ability to reduce fire damage by 50%? Figure it was just the burn protection & knockback resist while the Skull gives burn protection & reduces fire damage by 50% according to their tooltips.

**Comment by CursedFlames** [comment]
yes, obsidian/ankh shields have always had all the functionality of the obsidian skull, not just the burn protection.

**Comment by SonicX8000** [comment]
Didn't know that the Ankh Shield had that ability as well, interesting.
