### ISSUE TITLE
[request] recall potions with waystones compatibility

### ISSUE THREAD

**Issue by Shivaxi** [CursedFlames/BountifulBaubles#18]
Heya!  I'm not sure if this is possible but would love to see recall potions get a compatibility patch for Waystones.  Currently in my modpack RLCraft, I have waystones set to set your spawn point.  If using a recall potion after you set your spawn point with a Waystone, the recall potion teleports you somewhere completely random (since RLCraft has random spawns between 10,000 and -10,000).

**Comment by Ulysses2** [comment]
Also doesn't recognize if you set your spawn with the /spawnpoint command.

**Comment by Ulysses2** [comment]
Problem is that it's not checking isSpawnForced when calling getBedSpawnLocation for the player.

**Comment by CursedFlames** [comment]
Should be fixed with 4f7dc2c, hopefully. Will be in the next 1.12 release; let me know when you want a release for RLCraft since I'd rather not have a release for a single bugfix.

**Comment by Shivaxi** [comment]
Gotcha, well additionally I was hoping to get some config options for drop chances of certain items like bezoar from cave spider.  Would love to tweak these a bit.
