### ISSUE TITLE
Baubble Crashes

### ISSUE THREAD

**Issue by ghost** [CursedFlames/BountifulBaubles#22]
It seems that we are having crashes whenever holding a horseshoe or shulker charm and we get shot by a baby shulker from baby mobs.
[crash-2019-12-06_13.05.46-server.txt](https://github.com/CursedFlames/BountifulBaubles/files/3932321/crash-2019-12-06_13.05.46-server.txt)

**Comment by CursedFlames** [comment]
Closing as 1.12 is no longer supported.
