### ISSUE TITLE
 Attack enemies flashback with this mod loaded, including the server

### ISSUE THREAD

**Issue by changyejava** [CursedFlames/BountifulBaubles#23]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2019-12-26 11:51:32 CST
Description: Unexpected error

java.lang.NoSuchMethodError: baubles.api.BaublesApi.isBaubleEquipped(Lnet/minecraft/entity/player/EntityPlayer;Lnet/minecraft/item/Item;)I
    at cursedflames.bountifulbaubles.item.ItemAmuletSinWrath.onCrit(ItemAmuletSinWrath.java:33)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_343_ItemAmuletSinWrath_onCrit_CriticalHitEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.common.ForgeHooks.getCriticalHit(ForgeHooks.java:1335)
    at net.minecraft.entity.player.EntityPlayer.attackTargetEntityWithCurrentItem(EntityPlayer.java:1289)
    at bettercombat.mod.client.handler.EventHandlersClient.onMouseLeftClick(EventHandlersClient.java:100)
    at bettercombat.mod.client.handler.EventHandlersClient.onMouseEvent(EventHandlersClient.java:52)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_550_EventHandlersClient_onMouseEvent_MouseEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.client.ForgeHooksClient.postMouseEvent(ForgeHooksClient.java:273)
    at net.minecraft.client.Minecraft.runTickMouse(Minecraft.java:2275)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1800)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['JM_Bin'/21, l='MpServer', x=927.83, y=6.55, z=97.64]]
  Chunk stats: MultiplayerChunkCache: 219, 219
  Level seed: 0
  Level generator: ID 01 - flat, ver 0. Features enabled: false
  Level generator options: 
  Level spawn location: World: (882,4,179), Chunk: (at 2,0,3 in 55,11; contains blocks 880,0,176 to 895,255,191), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
  Level time: 643 game time, 643 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
  Forced entities: 12 total; [EntitySlime['史莱姆'/66, l='MpServer', x=868.89, y=4.00, z=103.10], EntityButterfly['蝴蝶'/99, l='MpServer', x=932.45, y=5.45, z=103.82], EntityButterfly['蝴蝶'/100, l='MpServer', x=926.31, y=4.18, z=102.40], EntitySlime['史莱姆'/103, l='MpServer', x=895.89, y=4.00, z=102.48], EntityButterfly['蝴蝶'/104, l='MpServer', x=1004.24, y=6.72, z=175.43], EntityButterfly['蝴蝶'/106, l='MpServer', x=1008.31, y=6.06, z=176.50], EntitySlime['史莱姆'/110, l='MpServer', x=956.94, y=4.00, z=44.58], EntityButterfly['蝴蝶'/112, l='MpServer', x=926.13, y=5.47, z=99.83], EntitySlime['史莱姆'/48, l='MpServer', x=856.26, y=4.00, z=173.21], EntityPlayerSP['JM_Bin'/21, l='MpServer', x=927.83, y=6.55, z=97.64], EntitySlime['史莱姆'/119, l='MpServer', x=859.96, y=5.02, z=164.58], EntityButterfly['蝴蝶'/120, l='MpServer', x=1005.36, y=9.75, z=88.80]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 8.1 (amd64) version 6.3
  Java Version: 1.8.0_40, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1086915120 bytes (1036 MB) / 3154116608 bytes (3008 MB) up to 3154116608 bytes (3008 MB)
  JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx3000m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 94 mods loaded, 94 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                          | Version              | Source                                                   | Signature                                |
       |:------ |:--------------------------- |:-------------------- |:-------------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                   | 1.12.2               | minecraft.jar                                            | None                                     |
       | LCHIJA | mcp                         | 9.42                 | minecraft.jar                                            | None                                     |
       | LCHIJA | FML                         | 8.0.99.99            | forge-1.12.2-14.23.5.2838.jar                            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                       | 14.23.5.2838         | forge-1.12.2-14.23.5.2838.jar                            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | ivtoolkit                   | 1.3.3-1.12           | minecraft.jar                                            | None                                     |
       | LCHIJA | jei                         | 4.13.1.225           | [JEI][NEI前置]jei_1.12.2-4.13.1.225.jar                    | None                                     |
       | LCHIJA | codechickenlib              | 3.2.2.354            | [NEI前置]CodeChickenLib-1.12.2-3.2.2.354-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | nei                         | 2.4.2                | [NEI]NotEnoughItems-1.12.2-2.4.2.244-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | ic2                         | 2.8.164-ex112        | [工业时代2]industrialcraft-2-2.8.164-ex112.jar               | de041f9f6187debbc77034a344134053277aa3b0 |
       | LCHIJA | baubles                     | 1.5.1                | 前置Baubles-1.12-1.5.1.jar                                 | None                                     |
       | LCHIJA | bountifulbaubles            | 0.0.1                | Bountiful+Baubles-1.12.2-0.1.4.jar                       | None                                     |
       | LCHIJA | inventorytweaks             | 1.64+dev.146.2180b27 | R键整理-1.64+dev.146.jar                                    | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | joshxmas                    | 1.12.2-1.2.0         | 【Joshua的圣诞模组】joshxmas-1.12.2-1.2.0.jar                   | None                                     |
       | LCHIJA | biomesoplenty               | 7.0.1.2399           | 【世界-超多生态群系】BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar | None                                     |
       | LCHIJA | vanillafix                  | 1.0.10-SNAPSHOT      | 【优化-原版修复】VanillaFix-1.0.10-99.jar                        | None                                     |
       | LCHIJA | texfix                      | 4.0                  | 【优化-材质缓存优化】TexFix+V-1.12-4.0.jar                         | None                                     |
       | LCHIJA | veinminer                   | 0.38.2               | 【功能-连锁挖矿】VeinMiner-1.12-0.38.2.647+b31535a.jar           | None                                     |
       | LCHIJA | veinminermodsupport         | 0.38.2               | 【功能-连锁挖矿】VeinMiner-1.12-0.38.2.647+b31535a.jar           | None                                     |
       | LCHIJA | sct                         | 1.1.0                | 【巧妙的工作台】sct-1.1.1.jar                                    | None                                     |
       | LCHIJA | cfm                         | 5.3.1                | 【物品-家具】[1.12.2]MrCrayfish's Furniture - 5.3.1.jar        | None                                     |
       | LCHIJA | reforged                    | 0.7.5                | 【物品-更多武器】Reforged-Mod-1.12.jar                           | None                                     |
       | LCHIJA | oreshrubs                   | 1.4.4                | 【物品-矿山灌丛】oreshrubs-1.4.4-1.12.2.jar                      | None                                     |
       | LCHIJA | customnpcs                  | 1.12                 | 【自定义人物】CustomNPCs_1.12.2(26aug18).jar                    | None                                     |
       | LCHIJA | birdsfoods                  | 3.1 - [1.12]         | 【风味食物】birdsfoods-1.12+-+3.1.jar                          | None                                     |
       | LCHIJA | harvestcraft                | 1.12.2zb             | 【食物-潘马斯丰收工艺】Pam's+HarvestCraft+1.12.2zb.jar              | None                                     |
       | LCHIJA | aquaculture                 | 1.6.8                | 水产养殖-1.12.2-1.6.8.jar                                    | None                                     |
       | LCHIJA | vanillafoodpantry           | 4.3.0                | 【食物-食物储藏室】vanillafoodpantry-mc1.12.2-4.3.jar             | None                                     |
       | LCHIJA | potioncore                  | 1.8_for_1.12.2       | 药水核心-1.8_for_1.12.2.jar                                  | None                                     |
       | LCHIJA | qualitytools                | 1.0.7_for_1.12.2     | 优质工具（工具属性）-1.0.7_for_1.12.2.jar                          | None                                     |
       | LCHIJA | waystones                   | 4.0.72               | 传送石碑 Waystones_1.12.2-4.0.72.jar                         | None                                     |
       | LCHIJA | advanced-fishing            | 1.3.3                | 先进的捕鱼-1.12.2-1.3.3.jar                                   | None                                     |
       | LCHIJA | roguelike                   | 1.8.0                | 冒险地牢-1.12.2-1.8.0.jar                                    | None                                     |
       | LCHIJA | llibrary                    | 1.7.19               | 前置llibrary-1.7.19-1.12.2.jar                             | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHIJA | iceandfire                  | 1.7.1                | 冰与火-1.7.1-1.12.2.jar                                     | None                                     |
       | LCHIJA | alcatrazcore                | 1.0.4                | 前置alcatrazcore-1.0.4.jar                                 | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
       | LCHIJA | silentlib                   | 3.0.13               | 前置SilentLib-1.12.2-3.0.13+167.jar                        | None                                     |
       | LCHIJA | tschipplib                  | 1.1.3                | 前置TschippLib MC1.12.2 v1.1.3.jar                         | None                                     |
       | LCHIJA | dynamictrees                | 1.12.2-0.9.5         | 动态的树-1.12.2-0.9.5.jar                                    | None                                     |
       | LCHIJA | levelup2                    | ${version}           | 升级! 2-1.1.23-1.12.jar                                    | None                                     |
       | LCHIJA | soundfilters                | 0.11_for_1.12        | 华丽音效-0.11_for_1.12.jar                                   | None                                     |
       | LCHIJA | bettercombatmod             | 1.5.6                | 双持战斗-1.12.2-1.5.6.jar                                    | None                                     |
       | LCHIJA | trumpetskeleton             | 1.12-1.0.2.1         | 吹号小白-1.12-1.0.2.1.jar                                    | None                                     |
       | LCHIJA | dldungeonsjbg               | 1.12.10              | 地牢-1.12.10-MC1.12.2.jar                                  | None                                     |
       | LCHIJA | toughasnails                | 3.1.0.141            | 坚定意志-1.12.2-3.1.0.141-universal.jar                      | None                                     |
       | LCHIJA | tanspit                     | 1.12.2-1.3           | 坚定意志烤架-1.12.2-1.3.jar                                    | None                                     |
       | LCHIJA | multimine                   | 1.6.2                | 多人开采-1.12.2.jar                                          | None                                     |
       | LCHIJA | lostcities                  | 2.0.21               | 失落城市-1.12-2.0.21.jar                                     | None                                     |
       | LCHIJA | wearablebackpacks           | 3.1.4                | 旅行者背包-1.12.2-3.1.4.jar                                   | None                                     |
       | LCHIJA | corpsecomplex               | 1.0.6                | 尸体复杂（？）-1.12.2-1.0.6.jar                                 | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCHIJA | buildcraftlib               | 7.99.24.1            | 建筑[1.12.2]buildcraft-all-7.99.24.1.jar                   | None                                     |
       | LCHIJA | buildcraftcore              | 7.99.24.1            | 建筑[1.12.2]buildcraft-all-7.99.24.1.jar                   | None                                     |
       | LCHIJA | buildcraftbuilders          | 7.99.24.1            | 建筑[1.12.2]buildcraft-all-7.99.24.1.jar                   | None                                     |
       | LCHIJA | buildcrafttransport         | 7.99.24.1            | 建筑[1.12.2]buildcraft-all-7.99.24.1.jar                   | None                                     |
       | LCHIJA | buildcraftsilicon           | 7.99.24.1            | 建筑[1.12.2]buildcraft-all-7.99.24.1.jar                   | None                                     |
       | LCHIJA | buildcraftcompat            | 7.99.24.1            | 建筑[1.12.2]buildcraft-all-7.99.24.1.jar                   | None                                     |
       | LCHIJA | buildcraftenergy            | 7.99.24.1            | 建筑[1.12.2]buildcraft-all-7.99.24.1.jar                   | None                                     |
       | LCHIJA | buildcraftfactory           | 7.99.24.1            | 建筑[1.12.2]buildcraft-all-7.99.24.1.jar                   | None                                     |
       | LCHIJA | buildcraftrobotics          | 7.99.24.1            | 建筑[1.12.2]buildcraft-all-7.99.24.1.jar                   | None                                     |
       | LCHIJA | lycanitesmobs               | 2.0.0.9 - MC 1.12.2  | 恐怖生物1.12.jar                                             | None                                     |
       | LCHIJA | battletowers                | 1.6.5                | 战斗高塔-1.12.2.jar                                          | None                                     |
       | LCHIJA | reskillable                 | 1.12.2-GRADLE:BUILD  | 技能限制武器Reskillable-1.12.2-1.12.5.jar                      | None                                     |
       | LCHIJA | spartanshields              | 1.5.4                | 斯巴达之盾-1.12.2-1.5.4.jar                                   | None                                     |
       | LCHIJA | spartanweaponry             | beta 1.3.1           | 斯巴达武器-1.12.2-beta-1.3.1.jar                              | None                                     |
       | LCHIJA | notreepunching              | 2.0.20               | 无树可撸notreepunching-2.0.20.jar                            | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
       | LCHIJA | switchbow                   | 1.5.7                | 智能弓-1.5.7.jar                                            | None                                     |
       | LCHIJA | ironchest                   | 1.12.2-7.0.54.838    | 更多箱子.jar                                                 | None                                     |
       | LCHIJA | somanyenchantments          | 0.4.4                | 更多附魔 V0.4.4.jar                                          | None                                     |
       | LCHIJA | mujmajnkraftsbettersurvival | 1.3.4                | 更好的生存-1.3.4(1.12.1).jar                                  | None                                     |
       | LCHIJA | autoreglib                  | 1.3-32               | 植物魔法AutoRegLib-1.3-32.jar                                | None                                     |
       | LCHIJA | coralreef                   | 2.0                  | 水下珊瑚-2.5-1.12.2.jar                                      | None                                     |
       | LCHIJA | familiarfauna               | 1.0.11               | 熟悉的动物-1.12.2-1.0.11.jar                                  | None                                     |
       | LCHIJA | wolfarmor                   | 2.2.3.6              | 狼铠-1.12.2-2.2.3.1798-universal.jar                       | None                                     |
       | LCHIJA | comforts                    | 1.4.1.2              | 睡袋-1.12.2-1.4.1.2.jar                                    | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCHIJA | disenchanter                | 1.6                  | 祛魔台-[1.12]1.6.jar                                        | None                                     |
       | LCHIJA | campfire                    | 1.2                  | 篝火-1.12-v1.2.jar                                         | None                                     |
       | LCHIJA | infernalmobs                | 1.7.6                | 精英怪物-1.12.2.jar                                          | None                                     |
       | LCHIJA | xpbook                      | v1.1.1               | 经验书-1.12.2-v1.1.1.jar                                    | None                                     |
       | LCHIJA | defiledlands                | 1.4.2                | 腐化之地-1.12.2-1.4.2.jar                                    | None                                     |
       | LCHIJA | i18nmod                     | 1.12.2-1.0.8         | 自动汉化-1.12.2-1.0.8.jar                                    | None                                     |
       | LCHIJA | reccomplex                  | 1.4.8.2              | 自动生成建筑 1.4.8.2.jar                                       | None                                     |
       | LCHIJA | bloodmoon                   | 1.5.3                | 血月-MC1.12.2-1.5.3.jar                                    | d72e0dd57935b3e9476212aea0c0df352dd76291 |
       | LCHIJA | neat                        | 1.4-17               | 血条 1.4-17.jar                                            | None                                     |
       | LCHIJA | scalinghealth               | 1.3.37               | 血量调整-1.12.2-1.3.40+145.jar                               | None                                     |
       | LCHIJA | enhancedvisuals             | 1.0                  | 视觉效果增强_v1.2.6_mc1.12.2.jar                               | None                                     |
       | LCHIJA | rfa                         | 1.0.0                | 解锁全部合成RecipesForAll-1.0.0.jar                            | None                                     |
       | LCHIJA | forgottenitems              | 1.2.1                | 遗忘物品MC1.12.2 v1.2.1.jar                                  | None                                     |
       | LCHIJA | forgeendertech              | 1.12.2-4.4.22.2      | 遗忘者-1.12.2-4.4.22.2-build.0405.jar                       | None                                     |
       | LCHIJA | reborncore                  | 3.16.3.476           | 重生核心-1.12.2-3.16.3.476-universal.jar                     | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
       | LCHIJA | craftablechainmail          | 1.0                  | 锁链甲制作-1.0.jar                                            | None                                     |
       | LCHIJA | enchdesc                    | 1.1.19               | 附魔描述-1.12.2-1.1.19.jar                                   | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | foodexpansion               | 1.3                  | 食物扩张.jar                                                 | None                                     |
       | LCHIJA | xat                         | 0.25.2               | 饰品-1.12.2-0.25.2.jar                                     | None                                     |
       | LCHIJA | baubleshud                  | 5.0.2                | 饰品显示（9键）-1.12.2-5.0.2.jar                                | None                                     |
       | LCHIJA | craftablehorsearmour        | 1.3                  | 马具制作.jar                                                 | None                                     |
  Loaded coremods (and transformers): llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      CorePlugin (遗忘者-1.12.2-4.4.22.2-build.0405.jar)
                                        
                                      MMFMLCorePlugin (多人开采-1.12.2.jar)
                                        atomicstryker.multimine.common.fmlmagic.MMTransformer
                                      LoadingPlugin (血月-MC1.12.2-1.5.3.jar)
                                        lumien.bloodmoon.asm.ClassTransformer
                                      Inventory Tweaks Coremod (R键整理-1.64+dev.146.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      LoadingPlugin (技能限制武器Reskillable-1.12.2-1.12.5.jar)
                                        codersafterdark.reskillable.base.asm.ClassTransformer
                                      VanillaFixLoadingPlugin (【优化-原版修复】VanillaFix-1.0.10-99.jar)
                                        
                                      IvToolkit (【前置】IvToolkit-1.3.3-1.12.jar)
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 441.41' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
  RebornCore: Plugin Engine: 0
              RebornCore Version: 3.16.3.476
              Runtime Debofucsation 1
              RenderEngine: 1
  Suspected Mods: Bountiful Baubles (bountifulbaubles), Better Combat Rebirth (bettercombatmod)
  Launched Version: HMCL 3.2.137
  LWJGL: 2.9.4
  OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 441.41, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: Minecraft-Mod-Language-Modpack.zip, Soartex_Fanver.zip
  Current Language: 简体中文 (中国)
  Profiler Position: N/A (disabled)
  CPU: 16x AMD Ryzen 7 1700 Eight-Core Processor
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0

**Comment by changyejava** [comment]
Attack Enemy Game Crashed Load (BountifulBaubles)

**Comment by CursedFlames** [comment]
Closing as 1.12 is no longer supported.
