### ISSUE TITLE
Items that have seperate recipes if you have mods, it seems to default to modded recipe

### ISSUE THREAD

**Issue by Pop000100** [CursedFlames/BountifulBaubles#27]
![issue](https://user-images.githubusercontent.com/20156032/77502805-c44af400-6e10-11ea-944c-99658364bacc.png)
I don't have a mod that has Enderium ingots, also tried to make a crown but i don't have rubies and diamonds didn't work
i will admit that java is not something i'm that fluent.

**Comment by CursedFlames** [comment]
Closing as 1.12 is no longer supported.
