### ISSUE TITLE
[BUG] Bauble bonuses not stacking/canceling out

### ISSUE THREAD

**Issue by kil0byt3** [CursedFlames/BountifulBaubles#28]
please see below for detailed report.

https://github.com/CalaMariGold/Rebirth-Of-The-Night/issues/112

Let me know if there's any other info I can provide.

**Comment by Setadokalo** [comment]
I think this might be a known issue... I'll look into it

**Comment by Setadokalo** [comment]
BountifulBaubles doesn't overwrite jump height, it adds to it. The issue here is most likely on QualityTools' side.

**Comment by kil0byt3** [comment]
Got it - thanks.
