### ISSUE TITLE
[1.12.2] Broken Heart Bauble oddness.

### ISSUE THREAD

**Issue by SonicX8000** [CursedFlames/BountifulBaubles#3]
Minecraft: 1.12.2
Forge: 14.23.5.2808

Mods: 6
Baubles-1.12-1.5.2
Bountiful+Baubles-1.12.2-0.0.1
FlameLib-1.12.2-0.0.7
jei_1.12.2-4.14.4.264
ScalingHealth-1.12.2-1.3.32-134
SilentLib-1.12.2-3.0.12+165

-----
Doing some testing with Scaling Health's damage source scaling just to see if the Broken Heart Bauble worked well... it seems that the Broken Heart Bauble is kinda iffy when it comes to damage reductions or can somehow give a damage reduction itself.

With scaling health config... I have Cactus Damage set at 5.0 with difficulty at 100 with a weight of 0.2 & my max health is set at 100. This is the kind of damage I take when I walk into a cactus according to the debug info from scaling health.

"[Scaling Health]: Damage scaling: type=cactus, scale=5.0, affected=20.0, change=100.0, original=1.0"

Now some tests... with armor & protection & such. No Broken Heart. ToroHUD was used since it shows a damage particle although it rounds up the damage.

No Armor:
*101 Damage*
Diamond Armor Set:
*85 Damage*
Diamond Armor Protection IV Set:
*31 Damage*

Now some tests... with armor & protection & such. Broken Heart is equipped with 'Fleeting' Modifier. Max Health is still 100.

No Armor:
*99 damage, 2 damage affected Max HP.*
Diamond Armor Set:
*83 Damage, 2 damage affected Max HP, damage wasn't Lethal*
Diamond Armor Protection IV Set:
*30 Damage, 2 damage affected Max HP,damage wasn't Lethal*

Now currently my health is 70/98 after taking damage with the Protection IV Diamond Armor Set from the cactus, I un-equip my armor and take damage again...

*69 damage, 32 damage affected Max HP, leaving me with 1/66 health. Damage was Lethal but apparently survived as it left me with 1 HP somehow despite the damage taken with no armor was 101.*

I'm aware that this is the first release so there may be some bugs out there but just kinda wonder if the Broken Heart is suppose to do this kind of thing... also... there are modded Damage Sources such as RPG Inventory's Buffed Gloves which gives a 20% damage reduction and Angel of Vengeance with has a spell called "Shield of Faith" that reduces all damage taken by 50% which could make the Broken Heart think that damage was Lethal.

To add on... it doesn't appear to account for Absorb Hearts. I give myself 20 Absorb and I have 100 Max HP which totals to 120 overall health. I walk into the cactus with no armor and I take 99 damage but apparently the Broken heart thought the damage was Lethal even though the damage was 101... so 2 of the damage affected Max HP despite having 21/98 remaining health. The next hit after that looks to be correct as I took 20 damage with 81 of the damage affecting Max HP leaving me with 1/17 health.

**Comment by CursedFlames** [comment]
Absorption and armor not being used should be fixed with 0418b08.
This might also allow for modded damage reduction, but I haven't tested any.
 Will be included in the next release.

**Comment by SonicX8000** [comment]
It works with modded damage reductions by the looks of it using AoV's Shield of Faith for the 50% damage reduction as well as Absorb Hearts. I'll have to keep a eye on it just to see if anything appears off but so far it works.
