### ISSUE TITLE
Using recall potion while on horse "softlocking" player

### ISSUE THREAD

**Issue by Keaen** [CursedFlames/BountifulBaubles#31]
While using a recall potion while riding a horse gets the user soft-locked in a glitch state where they are still where they were but the area appears to keep unloading and reloading rapidly ( at least thats what it looked like to me). 
Was using RL craft while this happened to me. tried to take screenshots, but they looked normal. 

only happened while a sufficient distance from the spawn point.
occasionally the teleport would actually go through, still stuck on the other end.
(looked like how it looks when you step on an unloaded chunk)

**Comment by CursedFlames** [comment]
Looks like this only happens on 1.12. Should be fixed with 829cce7.
