### ISSUE TITLE
toolbelts and jump height

### ISSUE THREAD

**Issue by TSCGCobra043** [CursedFlames/BountifulBaubles#36]
So a problem I just ran into was that if I put on a toolbelt (at least with springy quality) I don't jump as high as I normally would, I have springy pants, high jump II on my boots, and a balloon so I should be jumping about 3 blocks, but if I put on my toolbelt which has springy quality, I actually jump lower.[https://streamable.com/p103gp](url)

**Comment by Setadokalo** [comment]
Known issue, problem's on quality tools' end. Nothing we can do to fix it.
