### ISSUE TITLE
[Suggestion] Add feature to enable modifiers externally

### ISSUE THREAD

**Issue by Andyghandi** [CursedFlames/BountifulBaubles#37]
As a Terraria fan I really enjoyed the modifiers system, which i do with this mod as well. However, I think a neat feature would be to add an option to have the modifiers be able to be applied to other items and weapons. I know quality tools kinda does this, but I can't get that mod to work in the MC.eternal modpack, due to some ID 256 being exceeded. 

This could be done by either applying a random modifier once the item hits your inventory, or apply the modifier manually in the reforging station. 

I'm playing with forge 1.12.2

**Comment by CursedFlames** [comment]
I have no plans of developing new content for 1.12; Quality Tools also fills this niche rather nicely.
