### ISSUE TITLE
[1.16.1] Unable to regenerate heart containers after using Broken Heart 

### ISSUE THREAD

**Issue by NielsPilgaard** [CursedFlames/BountifulBaubles#40]
The Broken Heart bauble states that heart containers lost due to the Broken Heart being triggered can be regenerated by sleeping - That is currently not the case. Dying helps though :D

### Versions
- Bountiful Baubles FORGE-1.16.1-0.0.1

**Comment by CursedFlames** [comment]
Tracking this issue in #41 since there's more info there; as such I'll close this one even though it was made earlier
