### ISSUE TITLE
[1.15.2] Sleeping doesn't regenerate max hearts lost due to the Broken Heart

### ISSUE THREAD

**Issue by Shados** [CursedFlames/BountifulBaubles#41]
To reproduce:
1. Equip the Broken Heart, go take lethal damage
2. Note the loss of max heart containers
3. Go to sleep
4. Observe that the missing max heart containers are *visually* restored, but you can't actually regenerate health into them -- it appears to just be a visual bug
5. Disconnecting and reconnecting reveals that the heart containers are still gone

Dying does usually reset the lost heart containers, although on at least one occasion it instead somehow left me with *no* heart containers at all, which was amusing.

**Comment by Thombias** [comment]
Can confirm this is also the case for the 1.16.3 port. However the missing empty heart containers don't visually get restored after sleeping, they always stay gone.

**Comment by CursedFlames** [comment]
> Disconnecting and reconnecting

Sounds like this is a multiplayer issue then? I'll look into it soon.

**Comment by CursedFlames** [comment]
Changed the mechanic for maxhp regen with 236d5fc; this'll no longer be an issue as a result.
