### ISSUE TITLE
[Feature Suggestion] Make the obsidian shield and ankh shield craftable

### ISSUE THREAD

**Issue by MoreKerosine** [CursedFlames/BountifulBaubles#45]
In the game they're from, you can combine the cobalt shield and obsidian skull to get the obsidian shield, and combine that with the ankh charm to get the shield. I feel like it would make sense to carry this over to the mod as well.

**Comment by CursedFlames** [comment]
This is how it already works, unless something's broken. They're combined at an anvil, like other curio combos
