### ISSUE TITLE
Suggestion: Config options to disable wormhole and recall?

### ISSUE THREAD

**Issue by rfwainug** [CursedFlames/BountifulBaubles#5]
So far I've had the pleasure and enjoying and loving your mod and believe me, I've tried to disable them with CraftTweaker to no avail, your potions just don't stop being craftable. On a server, this proves to be something abusive, easily so and annoying to deal with. Very game-breaking and cheap to make, the sheer harassment that can be done with them (mainly wormhole) is a very bad sign for anyone attempting to make a decent, balanced modpack for servers in fairness of game play. Please add options to disable these features.

**Comment by CursedFlames** [comment]
CraftTweaker not being able to disable brewing recipes is strange, I'll have to investigate that later. In the meantime, 576736e adds a config option to disable brewing recipes.
