### ISSUE TITLE
Flame Lib missing from gradle dependencies

### ISSUE THREAD

**Issue by Kovak** [CursedFlames/BountifulBaubles#6]
I assume you probably provide it locally or something like that, but atm its not possible to really clone this library and get to developing.

**Comment by Kovak** [comment]
albedo is also missing

**Comment by CursedFlames** [comment]
The FlameLib dep is no longer relevant since the dependency was removed, and it looks like I did add the albedo dependency to build.gradle at some point, although I'm not 100% sure that it works.
