### ISSUE TITLE
Latest 1.12.2 Version has dependency flagged for Curios

### ISSUE THREAD

**Issue by Caervec** [CursedFlames/BountifulBaubles#61]
When downloading the latest update for Bountiful Baubles, it forced Curios (the 1.16 version) to download. I believe this file may accidentally have dependency flagged for Curios instead of Baubles.

**Comment by Caervec** [comment]
Checking the actual file page on Curseforge confirms: yes, Curios is flagged as the dependency not Baubles.

**Comment by CursedFlames** [comment]
ah dangit curseforge

**Comment by CursedFlames** [comment]
Should be fixed now.

**Comment by Caervec** [comment]
Thanks!
